name: publish to TestPyPi

on: workflow_dispatch

jobs:
    build:
      uses: ./.github/workflows/build.yml

    publish-to-testpypi:
        name: Publish Python 🐍 distribution 📦 to TestPyPI
        needs:
        - build
        runs-on: ubuntu-latest

        environment:
            name: testpypi
            url: https://test.pypi.org/project/mdi-pil/

        permissions:
            id-token: write

        steps:
          - name: Download all the dists
            uses: actions/download-artifact@v4
            with:
                name: python-package-distributions
                path: dist/
          - name: Publish distribution 📦 to TestPyPI
            uses: pypa/gh-action-pypi-publish@release/v1
            with:
                repository-url: https://test.pypi.org/legacy/
